version: '3.3'

services:

  grafana:
    image: 'grafana/grafana:6.2.5'
    ports:
      - '3030:3000'
    depends_on:
      - prometheus
      - prometheus_pushgateway
    volumes:
      - './grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasource.yml'
      - './dashboards/grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/grafana-dashboard.yml'
      - './dashboards/jvmgc-dashboard.json:/etc/grafana/dashboards/jvmgc.json'
      - './dashboards/latency-dashboard.json:/etc/grafana/dashboards/latency.json'
      - './dashboards/processor-dashboard.json:/etc/grafana/dashboards/processor.json'
      - './dashboards/business.json:/etc/grafana/dashboards/business.json'
      - './dashboards/schedulers.json:/etc/grafana/dashboards/schedulers.json'
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: Main Org.
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin

  prometheus:
    image: 'prom/prometheus:v2.13.1'
    ports:
      - '9090:9090'
    depends_on:
      - prometheus_pushgateway
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'

  prometheus_pushgateway:
    image: prom/pushgateway:v1.0.0
    ports:
      - "9091:9091"