management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus

  metrics:
    export:
      prometheus:
        pushgateway:
          push-rate: 1s
          enabled: true

    distribution:
      percentiles-histogram:
        reactor:
          onNext:
            delay: true